### ISSUE TITLE
Compile multiple files at once

### ISSUE THREAD

**Issue by dar5hak** [Feation/Feation#14]
#13 opens up the possibility to add multiple files for compilation, which is easy: just wrap the compilation code in a `forEach()`. I can do it if you think it makes sense.

However, before doing that, I would like to ask how you want the `-r` flag to behave in case of multiple source files:

1. Run all of them, or
2. Refuse to run, and specify that the `-r` flag can take only one arg.

**Comment by danilolekovic** [comment]
Run all of them, yes :+1: Thanks, @dar5hak!
