### ISSUE TITLE
Integrate a linter

### ISSUE THREAD

**Issue by dar5hak** [Feation/Feation#18]
As our code base grows, we'll need a way to streamline the coding style and follow best practices, and we need a linter for that. We'll also need a build tool to make linting (and testing, etc.) a one-command affair.

Do you have any preferences in linters and build tools? If not, I can go ahead and add Gulp + ESLint.

**Comment by mikebolt** [comment]
I recently set up a gulp build system with a linter. I started with jslint but switched to jshint. Jshint has more options and is more configurable. In either case there are decisions to make about what should be reported.

**Comment by mikebolt** [comment]
My mistake, I read "ESLint" as "jslint". ESLint does both static analysis and style checking, so you have to figure out what is important.

**Comment by danilolekovic** [comment]
I've never had any experience with linters :)

**Comment by dar5hak** [comment]
A linter basically reads through your source code and points out any potential problem cases or inconsistencies, and enforces best practices. Almost every npm project you'll see will have a `.eslintrc` or `.jshintrc` file, which are linter configs.

Wait, I'll show you.

**Comment by danilolekovic** [comment]
Alright :smiley:

**Comment by dar5hak** [comment]
There. Now, after merging this, you can just type `gulp static` and it will evaluate the code. As of now, it shows some 257 errors, but don't worry. I'll be fixing those. This is normal in the first run.
