### ISSUE TITLE
Obliterate loose equality and loose inequality

### ISSUE THREAD

**Issue by mikebolt** [Feation/Feation#8]
I think it would be a wonderful feature if the transpilation of Feation could never produce JavaScript's loose equality operators. == and != should be the only equality operators, and they should be strict, the same as JavaScript's === and !==. Read the answer to this question if you're wondering what I'm talking about: http://stackoverflow.com/questions/359494/does-it-matter-which-equals-operator-vs-i-use-in-javascript-comparisons. If type coercion of some kind is desired, nothing is preventing someone from writing, for example, a Feation library providing functions that do type coercion, so that you could write something like `if looseEquals(a, b)`.

**Comment by danilolekovic** [comment]
Thanks for the suggestion! :+1:  Committed at b5a144903bd7f6831625522c140490497d2d5e95.
